name: todo_app
description: A simple TODO app just for learning Flutter and firebase.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  firebase_auth:
  intl:
  font_awesome_flutter: ^8.7.0
  flutter_svg: ^0.17.1
  uuid: ^2.0.4
  localstorage: ^3.0.0
  validators: ^2.0.0
  curved_navigation_bar: ^0.3.2
  flutter_spinkit: "^4.1.2"
  giffy_dialog: ^1.7.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
